<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

# Hands-on Lab: API Examples
## Random User and Fruityvice API Examples


Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Load and use RandomUser API, using `RandomUser()` Python library
*   Load and use Fruityvice API, using `requests` Python library
*   Load and use Open-Joke-API, using `requests` Python library

The purpose of this notebook is to provide more examples on how to use simple APIs. As you have already learned from previous videos and notebooks, API stands for Application Programming Interface and is a software intermediary that allows two applications to talk to each other. 

The advantages of using APIs:
 *   **Automation**. Less human effort is required and workflows can be easily updated to become faster and more      
     productive.
 *   **Efficiency**. It allows to use the capabilities of one of the already developed APIs than to try to 
     independently implement some functionality from scratch.
 
The disadvantage of using APIs:
 *   **Security**. If the API is poorly integrated, it means it will be vulnerable to attacks, resulting in data breeches or losses having financial or reputation implications.

One of the applications we will use in this notebook is Random User Generator. RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more. More information on [RandomUser](https://randomuser.me/documentation#intro) can be found here.

Another example of simple API we will use in this notebook is Fruityvice application. The Fruityvice API web service which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The web service is completely free to use and contribute to.

## Example 1: RandomUser API
Bellow are Get Methods parameters that we can generate. For more information on the parameters, please visit this [documentation](https://randomuser.me/documentation) page.

## **Get Methods**

- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

To start using the API you can install the `randomuser` library running the `pip install` command.

In [1]:
!pip install randomuser
!pip install pandas

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py) ... one
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py) ... one
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5104 sha256=593e1e56dc839ae84008be345fa2fb0cf80b86843e6436b596cc9e93d57b7924
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/be/62/c8/71e1b48f4758ea5b78af7595d87178f628cde315a3326610ee
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6
Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 165.8 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 170.9 MB/s eta 0:00:00
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2

Then, we will load the necessary libraries.

In [2]:
from randomuser import RandomUser
import pandas as pd

First, we will create a random user object, r.

In [3]:
r = RandomUser()

Then, using `generate_users()` function, we get a list of random 10 users.

In [4]:
some_list = r.generate_users(10)

In [5]:
some_list

[<randomuser.RandomUser at 0x7db54bb96fc0>,
 <randomuser.RandomUser at 0x7db54bb96ff0>,
 <randomuser.RandomUser at 0x7db54bb97020>,
 <randomuser.RandomUser at 0x7db54bb97050>,
 <randomuser.RandomUser at 0x7db54bb97080>,
 <randomuser.RandomUser at 0x7db54bb970b0>,
 <randomuser.RandomUser at 0x7db54bb970e0>,
 <randomuser.RandomUser at 0x7db54bb97110>,
 <randomuser.RandomUser at 0x7db54bb97140>,
 <randomuser.RandomUser at 0x7db54bb97170>]

The **"Get Methods"** functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call `get_full_name()` function.

In [6]:
name = r.get_full_name()

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

In [7]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Odair Alves   odair.alves@example.com
Marinalda Sales   marinalda.sales@example.com
Angeles Roman   angeles.roman@example.com
Hannah Anderson   hannah.anderson@example.com
Ryan Jean-Baptiste   ryan.jean-baptiste@example.com
Nicole Smith   nicole.smith@example.com
Ethan Garcia   ethan.garcia@example.com
Isla Roberts   isla.roberts@example.com
Phyllis Reynolds   phyllis.reynolds@example.com
Gonzalo Gomez   gonzalo.gomez@example.com

## Exercise 1
In this Exercise, generate photos of the random 10 users.

In [9]:
## Write your code here
for user in some_list: 
    print(user.get_picture())

https://randomuser.me/api/portraits/men/68.jpg
https://randomuser.me/api/portraits/women/10.jpg
https://randomuser.me/api/portraits/women/75.jpg
https://randomuser.me/api/portraits/women/42.jpg
https://randomuser.me/api/portraits/men/96.jpg
https://randomuser.me/api/portraits/women/58.jpg
https://randomuser.me/api/portraits/men/66.jpg
https://randomuser.me/api/portraits/women/46.jpg
https://randomuser.me/api/portraits/women/72.jpg
https://randomuser.me/api/portraits/men/87.jpg

<details><summary>Click here for the solution</summary>

```python
for user in some_list:
    print (user.get_picture())
```

</details>

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [10]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [11]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Julie Hansen,female,Allinge,Hovedstaden,julie.hansen@example.com,1995-10-17T12:43:44.063Z,https://randomuser.me/api/portraits/women/80.jpg
1,Josefine Andersen,female,Snertinge,Midtjylland,josefine.andersen@example.com,1998-01-25T18:56:39.441Z,https://randomuser.me/api/portraits/women/15.jpg
2,Gabriel Esteban,male,Hospitalet de Llobregat,Comunidad Valenciana,gabriel.esteban@example.com,1944-09-12T16:47:02.902Z,https://randomuser.me/api/portraits/men/4.jpg
3,Niilo Lampo,male,Kärkölä,Central Finland,niilo.lampo@example.com,1974-08-30T01:22:50.295Z,https://randomuser.me/api/portraits/men/55.jpg
4,Finn Green,male,Wellington,Hawke'S Bay,finn.green@example.com,1971-08-16T20:56:51.254Z,https://randomuser.me/api/portraits/men/91.jpg
5,Noémie Singh,female,Woodstock,Newfoundland and Labrador,noemie.singh@example.com,1981-03-20T14:06:58.974Z,https://randomuser.me/api/portraits/women/73.jpg
6,Melike Duygulu,female,Sivas,Batman,melike.duygulu@example.com,1958-10-23T03:32:53.094Z,https://randomuser.me/api/portraits/women/17.jpg
7,Mason Tremblay,male,Hampton,Québec,mason.tremblay@example.com,1983-05-15T12:27:30.037Z,https://randomuser.me/api/portraits/men/36.jpg
8,Bobbie Green,female,Roseville,Minnesota,bobbie.green@example.com,1992-05-24T17:12:38.015Z,https://randomuser.me/api/portraits/women/13.jpg
9,Daniela Rodriguez,female,Pamplona,Melilla,daniela.rodriguez@example.com,1972-12-27T23:22:16.972Z,https://randomuser.me/api/portraits/women/33.jpg

In [12]:
df1 = pd.DataFrame(get_users())

Now we have a *pandas* dataframe that can be used for any testing purposes that the tester might have.

## Example 2: Fruityvice API

Another, more common way to use APIs, is through `requests` library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [13]:
import requests
import json

We will obtain the [fruityvice](https://www.fruityvice.com) API data using `requests.get("url")` function. The data is in a json format.

In [14]:
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")

We will retrieve results using `json.loads()` function.

In [15]:
results = json.loads(data.text)

We will convert our json data into *pandas* data frame.

In [ ]:
pd.DataFrame(results)

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [17]:
df2 = pd.json_normalize(results)

In [ ]:
df2

Let's see if we can extract some information from this dataframe. Perhaps, we need to know the family and genus of a cherry.

In [19]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

## Exercise 2
In this Exercise, find out how many calories are contained in a banana.

In [24]:
# Write your code here
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']

np.int64(96)

<details><summary>Click here for the solution</summary>

```python
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']
```

</details>

## Exercise 3

This [page](https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/) contains a list of free public APIs for you to practice. Let us deal with the following example.

#### Official Joke API 
This API returns random jokes from a database. The following URL can be used to retrieve 10 random jokes.

https://official-joke-api.appspot.com/jokes/ten

1. Using `requests.get("url")` function, load the data from the URL.

In [26]:
# Write your code here
data2 = requests.get("https://official-joke-api.appspot.com/jokes/ten")

<details><summary>Click here for the solution</summary>

```python
data2 = requests.get("https://official-joke-api.appspot.com/jokes/ten")
```

</details>

2. Retrieve results using `json.loads()` function.

In [28]:
# Write your code here
result2 = json.loads(data2.text)

<details><summary>Click here for the solution</summary>

```python
results2 = json.loads(data2.text)
```

</details>

3. Convert json data into *pandas* data frame. Drop the type and id columns.

In [30]:
# Write your code here
df3 = pd.DataFrame(result2)
df3.drop(columns = ['type','id'], inplace = True)
df3

,setup,punchline
0,What's the difference between a seal and a sea...,An ion!
1,What do you call a factory that sells passable...,A satisfactory
2,Knock-knock.,A race condition. Who is there?
3,How does a penguin build it’s house?,Igloos it together.
4,Did you hear about the cow who jumped over the...,It was udder destruction.
5,How do you make holy water?,You boil the hell out of it
6,what do you call a dog that can do magic tricks?,a labracadabrador
7,How did the hipster burn the roof of his mouth?,He ate the pizza before it was cool.
8,What is the least spoken language in the world?,Sign Language
9,"Due to complaints, Hawaii passed a law where y...",You can only use a low ha.

<details><summary>Click here for the solution</summary>

```python
df3 = pd.DataFrame(results2)
df3.drop(columns=["type","id"],inplace=True)
df3
```

</details>

# Congratulations! - You have completed the lab

## Author
<a href="https://www.linkedin.com/in/svitlana-kramar" target="_blank">Svitlana Kramar</a>

Svitlana is a master’s degree Data Science and Analytics student at University of Calgary, who enjoys travelling, learning new languages and cultures and loves spreading her passion for Data Science.

## Additional Contributor
<a href="https://www.linkedin.com/in/abhishek-gagneja-23051987/" target="_blank">Abhishek Gagneja</a>

Copyright © 2023 IBM Corporation. All rights reserved.